<script>
  export let data;
  export let backHref = '/';
  export let backLabel = 'Back';

  $: report = data?.report || {};
  $: projects = report?.projects || [];
  $: error = data?.error || '';

  function printReport() {
    window.print();
  }
</script>

<svelte:head>
  <title>{report?.title || 'Projects report'} | SGPA</title>
</svelte:head>

<main class="report-page">
  <section class="screen-actions">
    <a href={backHref} class="secondary-link">{backLabel}</a>

    <button type="button" class="print-btn" onclick={printReport}>
      Download PDF
    </button>
  </section>

  <article class="report-sheet">
    <header class="report-header">
      <div>
        <span class="institution">SGPA</span>
        <h1>{report?.title || 'Academic projects report'}</h1>
        <p>{report?.subtitle || 'Project report generated from the SGPA platform.'}</p>
      </div>

      <div class="report-mark">
        <span>S</span>
        <span>G</span>
        <span>P</span>
        <span>A</span>
      </div>
    </header>

    <section class="report-meta">
      <div>
        <span>Generated by</span>
        <strong>{report?.generatedBy || 'System user'}</strong>
      </div>

      <div>
        <span>Generated date</span>
        <strong>{report?.generatedAt || 'Not defined'}</strong>
      </div>

      <div>
        <span>Total projects</span>
        <strong>{projects.length}</strong>
      </div>
    </section>

    {#if error}
      <section class="report-error">
        <strong>Could not generate report.</strong>
        <p>{error}</p>
      </section>
    {:else if projects.length > 0}
      <section class="projects-list">
        {#each projects as project, index}
          <article class="project-block">
            <div class="project-number">{index + 1}</div>

            <div class="project-content">
              <div class="project-top">
                <div>
                  <h2>{project.project_name}</h2>
                  <p>{project.description}</p>
                </div>

                <span class="status-pill">{project.status}</span>
              </div>

              <div class="project-grid">
                <div>
                  <span>Project ID</span>
                  <strong>{project.id_project}</strong>
                </div>

                <div>
                  <span>Start date</span>
                  <strong>{project.start_date}</strong>
                </div>

                <div>
                  <span>End date</span>
                  <strong>{project.end_date}</strong>
                </div>

                <div>
                  <span>Assigned teacher</span>
                  <strong>{project.teacher?.name || 'Unassigned'}</strong>
                </div>
              </div>

              <div class="participants">
                <h3>Participants</h3>

                <div class="participant-line">
                  <strong>Teacher:</strong>
                  <span>
                    {project.teacher
                      ? `${project.teacher.name} - ${project.teacher.email}`
                      : 'No teacher assigned'}
                  </span>
                </div>

                <div class="participant-line students-line">
                  <strong>Students:</strong>

                  {#if project.students.length > 0}
                    <ul>
                      {#each project.students as student}
                        <li>{student.name} - {student.email}</li>
                      {/each}
                    </ul>
                  {:else}
                    <span>No students enrolled.</span>
                  {/if}
                </div>
              </div>
            </div>
          </article>
        {/each}
      </section>
    {:else}
      <section class="empty-report">
        <h2>No projects to report</h2>
        <p>There are no projects available for this report.</p>
      </section>
    {/if}

    <footer class="report-footer">
      <p>
        This report was generated automatically by the Academic Project Management System.
      </p>
    </footer>
  </article>
</main>

<style>
  .report-page {
    min-height: 100vh;
    padding: 2rem 1rem 3rem;
    background:
      radial-gradient(circle at top right, rgba(242, 183, 5, 0.12), transparent 22rem),
      linear-gradient(180deg, #ffffff 0%, var(--sgpa-bg, #f6f8fc) 100%);
    color: var(--sgpa-text, #172033);
  }

  .screen-actions {
    width: min(980px, 100%);
    margin: 0 auto 1rem;
    display: flex;
    justify-content: flex-end;
    gap: 0.75rem;
    flex-wrap: wrap;
  }

  .secondary-link,
  .print-btn {
    min-height: 44px;
    padding: 0.75rem 1.05rem;
    border-radius: 999px;
    font-weight: 950;
    text-decoration: none;
    display: inline-flex;
    align-items: center;
    justify-content: center;
  }

  .secondary-link {
    background: #ffffff;
    color: var(--sgpa-blue, #0b2d69);
    border: 1px solid var(--sgpa-border, #dbe4f0);
    box-shadow: var(--sgpa-shadow-sm, 0 8px 18px rgba(15, 35, 70, 0.08));
  }

  .print-btn {
    border: none;
    color: #ffffff;
    background: linear-gradient(135deg, var(--sgpa-blue, #0b2d69), var(--sgpa-blue-mid, #174ea6));
    cursor: pointer;
    box-shadow: 0 12px 26px rgba(11, 45, 105, 0.18);
  }

  .secondary-link:hover,
  .print-btn:hover {
    transform: translateY(-1px);
  }

  .report-sheet {
    width: min(980px, 100%);
    margin: 0 auto;
    padding: 2rem;
    border-radius: 28px;
    background: #ffffff;
    border: 1px solid var(--sgpa-border, #dbe4f0);
    box-shadow: var(--sgpa-shadow-md, 0 16px 36px rgba(15, 35, 70, 0.1));
  }

  .report-header {
    display: flex;
    justify-content: space-between;
    gap: 1.5rem;
    align-items: flex-start;
    padding-bottom: 1.2rem;
    border-bottom: 4px solid var(--sgpa-yellow, #f2b705);
  }

  .institution {
    display: inline-flex;
    width: fit-content;
    margin-bottom: 0.6rem;
    padding: 0.38rem 0.75rem;
    border-radius: 999px;
    background: var(--sgpa-yellow-soft, #fff7d6);
    color: var(--sgpa-blue, #0b2d69);
    font-size: 0.78rem;
    font-weight: 950;
    letter-spacing: 0.08em;
    border: 1px solid rgba(242, 183, 5, 0.3);
  }

  .report-header h1 {
    margin: 0;
    color: var(--sgpa-blue-dark, #071f49);
    font-size: clamp(1.9rem, 4vw, 3rem);
    line-height: 1.05;
    font-weight: 950;
    letter-spacing: -0.045em;
  }

  .report-header p {
    max-width: 700px;
    margin: 0.7rem 0 0;
    color: var(--sgpa-text-soft, #64748b);
    line-height: 1.65;
  }

  .report-mark {
    width: 96px;
    height: 96px;
    border-radius: 24px;
    background: linear-gradient(135deg, var(--sgpa-blue, #0b2d69), var(--sgpa-blue-mid, #174ea6));
    color: #ffffff;
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    place-items: center;
    font-weight: 950;
    letter-spacing: 0.08em;
    box-shadow: 0 14px 32px rgba(11, 45, 105, 0.24);
    flex-shrink: 0;
  }

  .report-meta {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 0.85rem;
    margin: 1.2rem 0;
  }

  .report-meta div,
  .project-grid div {
    padding: 0.9rem;
    border-radius: 18px;
    background: var(--sgpa-bg, #f6f8fc);
    border: 1px solid var(--sgpa-border, #dbe4f0);
  }

  .report-meta span,
  .project-grid span {
    display: block;
    margin-bottom: 0.28rem;
    color: var(--sgpa-text-soft, #64748b);
    font-size: 0.78rem;
    font-weight: 850;
  }

  .report-meta strong,
  .project-grid strong {
    color: var(--sgpa-blue-dark, #071f49);
    font-weight: 950;
  }

  .projects-list {
    display: grid;
    gap: 1.15rem;
  }

  .project-block {
    display: grid;
    grid-template-columns: 46px 1fr;
    gap: 1rem;
    padding: 1.1rem;
    border-radius: 22px;
    border: 1px solid var(--sgpa-border, #dbe4f0);
    background: #ffffff;
    page-break-inside: avoid;
  }

  .project-number {
    width: 42px;
    height: 42px;
    border-radius: 15px;
    display: grid;
    place-items: center;
    color: #ffffff;
    background: var(--sgpa-blue, #0b2d69);
    font-weight: 950;
  }

  .project-top {
    display: flex;
    justify-content: space-between;
    gap: 1rem;
    align-items: flex-start;
    margin-bottom: 0.9rem;
  }

  .project-top h2 {
    margin: 0;
    color: var(--sgpa-blue-dark, #071f49);
    font-size: 1.35rem;
    font-weight: 950;
  }

  .project-top p {
    margin: 0.35rem 0 0;
    color: var(--sgpa-text-soft, #64748b);
    line-height: 1.6;
  }

  .status-pill {
    display: inline-flex;
    width: fit-content;
    padding: 0.42rem 0.82rem;
    border-radius: 999px;
    background: var(--sgpa-blue-soft, #e8f0ff);
    color: var(--sgpa-blue, #0b2d69);
    border: 1px solid rgba(11, 45, 105, 0.12);
    font-size: 0.82rem;
    font-weight: 950;
    flex-shrink: 0;
  }

  .project-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 0.75rem;
    margin-bottom: 1rem;
  }

  .participants {
    padding-top: 0.8rem;
    border-top: 1px solid var(--sgpa-border, #dbe4f0);
  }

  .participants h3 {
    margin: 0 0 0.55rem;
    color: var(--sgpa-blue-dark, #071f49);
    font-size: 1rem;
    font-weight: 950;
  }

  .participant-line {
    color: var(--sgpa-text-soft, #64748b);
    line-height: 1.7;
  }

  .participant-line strong {
    color: var(--sgpa-blue-dark, #071f49);
  }

  .students-line ul {
    margin: 0.4rem 0 0;
    padding-left: 1.2rem;
  }

  .students-line li::marker {
    color: var(--sgpa-yellow, #f2b705);
  }

  .empty-report,
  .report-error {
    padding: 2rem;
    border-radius: 22px;
    background: var(--sgpa-bg, #f6f8fc);
    border: 1px dashed var(--sgpa-border, #dbe4f0);
    text-align: center;
  }

  .report-error {
    background: var(--sgpa-danger-bg, #fee2e2);
    color: var(--sgpa-danger, #dc2626);
  }

  .report-footer {
    margin-top: 1.2rem;
    padding-top: 1rem;
    border-top: 1px solid var(--sgpa-border, #dbe4f0);
    color: var(--sgpa-text-soft, #64748b);
    font-size: 0.86rem;
    text-align: center;
  }

  @media (max-width: 820px) {
    .report-header,
    .project-top {
      flex-direction: column;
    }

    .report-meta,
    .project-grid {
      grid-template-columns: 1fr;
    }

    .project-block {
      grid-template-columns: 1fr;
    }
  }

  @media print {
    @page {
      size: A4;
      margin: 14mm;
    }

    body {
      background: #ffffff !important;
    }

    .screen-actions {
      display: none !important;
    }

    .report-page {
      padding: 0;
      background: #ffffff !important;
    }

    .report-sheet {
      width: 100%;
      padding: 0;
      border: none;
      border-radius: 0;
      box-shadow: none;
    }

    .project-block {
      break-inside: avoid;
      page-break-inside: avoid;
    }

    .report-mark {
      box-shadow: none;
    }
  }
</style>